# Generated by Django 3.0.6 on 2020-05-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default=None)),
                ('logo', models.ImageField(blank=True, default=None, upload_to='')),
                ('date', models.DateTimeField(default=None)),
                ('can_register', models.BooleanField(default=False)),
                ('feedback_link', models.URLField(blank=True, default=None)),
                ('photos_link', models.URLField()),
                ('registration_date', models.DateTimeField(default=None)),
                ('registration_link', models.URLField()),
            ],
        ),
    ]
