# Generated by Django 3.0.6 on 2020-05-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='logo',
            field=models.ImageField(blank=True, default=None, upload_to='images/'),
        ),
    ]
