# Generated by Django 3.0.6 on 2020-05-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200531_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='logo',
            field=models.ImageField(blank=True, default=None, upload_to='static/'),
        ),
    ]
