# Generated by Django 3.0.6 on 2020-06-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200531_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='can_register',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='photos_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='events',
            name='registration_link',
            field=models.URLField(blank=True),
        ),
    ]
