# Generated by Django 3.0.6 on 2020-06-01 14:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200601_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
