# Generated by Django 3.0.6 on 2020-07-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rlink', models.URLField(max_length=1000)),
                ('rtype', models.CharField(max_length=50)),
                ('rdesp', models.CharField(max_length=300)),
                ('rlink_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.Resource')),
            ],
        ),
    ]
