# Generated by Django 3.0.6 on 2020-06-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelinks',
            name='rfiles',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
