# Generated by Django 3.0.6 on 2020-06-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcelinks',
            name='rfiles',
        ),
    ]
