# Generated by Django 3.0.6 on 2020-07-03 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitive_programming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_time',
            name='server_update_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 18, 55, 15, 915598)),
        ),
    ]
