# Generated by Django 3.0.6 on 2020-06-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitive_programming', '0002_pclub_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pclub_contest',
            name='contest_duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='pclub_contest',
            name='contest_end',
            field=models.DateTimeField(blank=True),
        ),
    ]
