# Generated by Django 3.0.6 on 2020-06-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitive_programming', '0003_auto_20200619_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pclub_contest',
            name='contest_duration',
            field=models.CharField(max_length=100),
        ),
    ]
