<<<<<<< HEAD
# Generated by Django 3.0.6 on 2020-06-10 08:06
=======
# Generated by Django 3.0.6 on 2020-06-11 06:56
>>>>>>> a54511f2ac45bf97f70583c8cc319734a999e7ff

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='faculty_advisor_photo',
            field=models.ImageField(blank=True, default=None, upload_to='images/'),
        ),
    ]
