# Generated by Django 3.0.6 on 2020-06-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_title', models.CharField(max_length=200)),
                ('announcement_date', models.DateTimeField(auto_now_add=True)),
                ('announcement_description', models.TextField()),
                ('announcement_image', models.ImageField(blank=True, default=None, upload_to='images/')),
            ],
        ),
    ]
