# Generated by Django 3.0.6 on 2020-06-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_title', models.CharField(max_length=200)),
                ('announcement_date', models.DateTimeField(auto_now_add=True)),
                ('announcement_description', models.TextField(max_length=730)),
                ('announcement_image', models.ImageField(blank=True, default='/static/images/announcement-dafault.png', upload_to='images/')),
                ('announcement_isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.CharField(blank=True, max_length=150, null=True)),
                ('question_isQuote', models.BooleanField(default=False)),
                ('question_tobeadded', models.DateField()),
            ],
        ),
    ]
