# Generated by Django 3.0.6 on 2020-06-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_announce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcement_isActive',
            field=models.BooleanField(default=True),
        ),
    ]
