# Generated by Django 3.0.6 on 2020-06-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_announce', '0002_announcement_announcement_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_description',
            field=models.TextField(max_length=730),
        ),
    ]
