# Generated by Django 3.0.6 on 2020-06-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_announce', '0002_remove_announcement_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcement_isofEvent',
            field=models.BooleanField(default=False),
        ),
    ]
