# Generated by Django 3.0.6 on 2020-06-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_announce', '0003_auto_20200622_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_image',
            field=models.ImageField(blank=True, default='/static/images/announcement-dafault.png', upload_to='images/'),
        ),
    ]
