# Generated by Django 3.0.6 on 2020-06-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_announce', '0004_auto_20200622_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=150)),
                ('question_isQuote', models.BooleanField(default=False)),
                ('question_tobeadded', models.DateField()),
            ],
        ),
    ]
