# Generated by Django 3.0.6 on 2020-06-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=300)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('join_whatsapp', models.BooleanField(default=False)),
            ],
        ),
    ]
